include: package:very_good_analysis/analysis_options.yaml

analyzer:
  exclude:
    - "**/*.config.dart"
    - packages/**
    - "**/*.g.dart"
    - "**/*.freezed.dart"
    - "**/*.gr.dart"
  
linter:
  rules:
    # Use parameter order as in json response
    always_put_required_named_parameters_first: true
    
    # Util classes are awesome!
    avoid_classes_with_only_static_members: false

    # Make constructors the first thing in every class
    sort_constructors_first: true

    # The new tabs vs. spaces. Choose wisely
    prefer_single_quotes: true
    prefer_double_quotes: false

    # Good packages document everything
    public_member_api_docs: true
    
    # Blindly follow the Flutter code style, which prefers types everywhere
    always_specify_types: true

    # Omit local types
    omit_local_variable_types: false

    # Back to the 80s
    lines_longer_than_80_chars: true